### ISSUE TITLE
Weekend file clarification

### ISSUE THREAD

**Issue by nkosihenry** [ardalis/kata-catalog#6]
for \#7 When creating a fresh _weekend.txt_ file, what is done with the previous weekend's log file. is it overriden or renamed?

**Comment by ardalis** [comment]
Good question. I suggest renaming. I just clarified the instructions.

> Actually, the manager just gave us new requirements. The first time you log to a file on a new weekend, make sure you start with a fresh "weekend.txt" file. Rename the old one based on the date of the Saturday of that weekend, e.g. weekend-YYYYMMDD.txt.
